### PR TITLE
Last Milestone : Publishing the final version of Youtube Clone.

### PR DESCRIPTION
**Pull request by AhmedTohamy01**
In this milestone we finished the following points:

- Building the nav bar, add the required elements in it and make sure that all elements and icons in nav bar are aligned in the correct positions.

- Building the sidebar, add videos and video descriptions to it and make sure that the sidebar videos appear in the correct positions. 

- Building the main video section, add a real video in it and make sure that the video is aligned in the correct position.

- Building the controls section, add controls, buttons and icons to it (Ex: share , like, dis-like, subscribe, author avatar), add information about the video and author of the video, number of likes and dis-likes, . and make sure that all elements aligned in the correct positions.

### CODE REVIEW

**Comment by AhmedTohamy01** [comment]
Thank you for rapid response Christian, really appreciated .

**Comment by AhmedTohamy01** [comment]
Dear Christian, @christianotieno @JasemDuncan 

Thank you for your review, but let me explain my point of view regarding your comments: 

**Point No.1 : [REQUIRED] - ADD - The hamburger icon
Point No.4 - IMPLEMENT - The comment section**

For points 1 & 4, This is NOT mandatory in the project requirements and it's not a reason for refusing the project. please read project requirements, the goal is to know how to insert an icon, not to insert a specific icon itself. Also comments section is not in the project requirements. 

below is the project requirement shortcut list , and nothing from what you mentioned in it!

_**Requirements shortcut list**

As this is your first project, we prepared a shortcut list of requirements. This list is based on requirements written in the task description and will help you control your progress.
Please remember: In the upcoming tasks you should be able to create a similar shortcut list on your own.

**Navigation bar**
It has an embedded image that represents a logo.
The logo is aligned to the leftmost part of the navbar.
It has an input tag that represents a search bar.
The search bar is aligned to the middle of the navbar.
It has a button tag that represents the search button.
The search button is at the end (rightmost part) of the search bar.
It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar.

**Video**
It is displayed.
It shows the video title.
It shows the number of views.
It has like and dislike icons.
It has a share button.
It shows the avatar of the user who uploaded the video.
It has a subscribe button.

**Sidebar Recommended videos**
It shows the recommended video’s thumbnail preview (as image not as an actual video).
It shows the title of the video.
It shows the number of views._

Kindly review it and tell us where is anything about "comments" or "specific hamburger icon"!

**Point No.2  [REQUIRED] - FIX - The span of the embedded video
Point No.3 [REQUIRED] - FIX -The styling on the subscribe section
Point No.5 [REQUIRED] - FIX - The recommendation section**

For Points 2, 3 & 5. The problem is not from our side, the problem is that your screen width is different than our screen width. if you checked the live demo link which we submitted in the read me file you will find that these problems don't exist.  Again, making a fully responsive website is NOT from the project requirements. please read the requirements list above.

**[Point No.6 REQUIRED] - FIX - The errors with your markup**
Excuse me , but this is NOT and errors, read the message carefully, it's a "warning" NOT an "error, Big difference!

If you read the message it says that there are no headers for the section, and these section doesn't really have headers. there are no headers in the video section in the original youtube website!

Thank you for accepting the feedback, and by the way, the first TSE engineer didn't have all these comments, he just mentioned that there was not a summary in PR Request and he was right because this was required. 

**Hope this makes everything clear for you and i wish we can get the approval soon.**

**Comment by christianotieno** [comment]
> Dear Christian, @christianotieno @JasemDuncan
> 
> Thank you for your review, but let me explain my point of view regarding your comments:
> 
> **Point No.1 : [REQUIRED] - ADD - The hamburger icon Point No.4 - IMPLEMENT - The comment section**
> 
> For points 1 & 4, This is NOT mandatory in the project requirements and it's not a reason for refusing the project. please read project requirements, the goal is to know how to insert an icon, not to insert a specific icon itself. Also comments section is not in the project requirements.
> 
> below is the project requirement shortcut list , and nothing from what you mentioned in it!
> 
> _**Requirements shortcut list**
> 
> As this is your first project, we prepared a shortcut list of requirements. This list is based on requirements written in the task description and will help you control your progress.
> Please remember: In the upcoming tasks you should be able to create a similar shortcut list on your own.
> 
> **Navigation bar**
> It has an embedded image that represents a logo.
> The logo is aligned to the leftmost part of the navbar.
> It has an input tag that represents a search bar.
> The search bar is aligned to the middle of the navbar.
> It has a button tag that represents the search button.
> The search button is at the end (rightmost part) of the search bar.
> It has at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar.
> 
> **Video**
> It is displayed.
> It shows the video title.
> It shows the number of views.
> It has like and dislike icons.
> It has a share button.
> It shows the avatar of the user who uploaded the video.
> It has a subscribe button.
> 
> **Sidebar Recommended videos**
> It shows the recommended video’s thumbnail preview (as image not as an actual video).
> It shows the title of the video.
> It shows the number of views._
> 
> Kindly review it and tell us where is anything about "comments" or "specific hamburger icon"!
> 
> **Point No.2 [REQUIRED] - FIX - The span of the embedded video Point No.3 [REQUIRED] - FIX -The styling on the subscribe section Point No.5 [REQUIRED] - FIX - The recommendation section**
> 
> For Points 2, 3 & 5. The problem is not from our side, the problem is that your screen width is different than our screen width. if you checked the live demo link which we submitted in the read me file you will find that these problems don't exist. Again, making a fully responsive website is NOT from the project requirements. please read the requirements list above.
> 
> **[Point No.6 REQUIRED] - FIX - The errors with your markup**
> Excuse me , but this is NOT and errors, read the message carefully, it's a "warning" NOT an "error, Big difference!
> 
> If you read the message it says that there are no headers for the section, and these section doesn't really have headers. there are no headers in the video section in the original youtube website!
> 
> Thank you for accepting the feedback, and by the way, the first TSE engineer didn't have all these comments, he just mentioned that there was not a summary in PR Request and he was right because this was required.
> 
> **Hope this makes everything clear for you and i wish we can get the approval soon.**

Hello @AhmedTohamy01 You are absolutely right with this. I must admit I should have **NEVER**  requested on the above changes and passing them as a requirement without providing a link to prove why. Thank you for bringing this up with me. I appreciate it a lot.
That said, I have gone back and rechecked the guidelines and I must attest they are not present in the `Additional Microverse Requirements` section of Pathwright description. 

My full apology below; 👇 


```
I've just realized that the changes passed down as a requirement is not required in this first project.
I am sorry to mislead you. I haven't done that on purpose :blush: Please go ahead and resubmit for another review, consider these required changes invalid. Thank you!
```

**Comment by AhmedTohamy01** [comment]
@christianotieno @JasemDuncan 

Dear Christian,

Thank you for accepting the feedback, this shows high proficiency from you .

I don't have any option to request the code review again, it just redirect me to  the form after the code review. I think you have to accept it direct, i didn't get a rejection to submit it again.

Please approve it and let me know when you did.

**Comment by christianotieno** [comment]
Hello @AhmedTohamy01, I just left you a message on slack regarding the same. 😄

**Comment by AhmedTohamy01** [comment]
so, what should we do to get approved now ? @christianotieno

**Comment by christianotieno** [comment]
Kindly share with me the screenshot of your dashboard on slack and let's continue with discussion there, please.

**Comment by AhmedTohamy01** [comment]
Okay Christian, I found a way and submitted it again, please approve and notify me @christianotieno 

Thanks

**Pull request merged**
